#!/bin/sh -e
if test \! -d package || test \! -d debian
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi
if [ $# -lt 2 ]
then
	echo "usage: $0 name staging-dir" 1>&2
	exit 100
fi
name="$1"
dir="$2"
install -d -- "${dir}"/DEBIAN
exec dpkg-gencontrol -p"${name}" -P"${dir}"
