#!/bin/sh
# (c) Copyright 2001,2002,2017 Jonathan de Boyne Pollard. "Moral" rights asserted.
# For the copyright licence, see COPYING.
for i do (
	cd "$i"
	test -d service && cd service
	echo "$i" | sed -e 's/./*/g'
	echo "$i"
	echo "$i" | sed -e 's/./*/g'
	echo
	echo '+++ Configuration options:'
	egrep '[A-Za-z0-9_]+=' run
	( cd env 2>/dev/null && grep "^" /dev/null * )
	echo
	echo '+++ Authorised client IP address prefixes:'
	ls -1 root/ip
	echo
	echo '+++ Hardwired content server IP addresses:'
	cd root/servers && grep "^" /dev/null *
	echo
); done
