#!/bin/sh -e
# See http://skarnet.org./software/compile.html
if [ \! -d package -o \! -d source ]
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
install -d -- command manual config doc header library

# ##############################################################################
# Build all of the ...{new} files in ./command, ./config, and ./manual.
cat package/commands1 package/commands8 | while read i
do
	rm -f -- command/"$i"{new}
	install -p -m 0755 -- build/"$i" command/"$i"{new}
	if objdump -a command/"$i"{new} >/dev/null 2>&1
	then
		 strip command/"$i"{new}
	fi
done
# All of the commands that have their own manual pages
cat package/commands1 package/extra-manpages1 | 
while read i
do
	rm -f -- manual/"$i".1{new}
	install -p -m 0644 -- build/"$i".1 manual/"$i".1{new}
	rm -f -- doc/"$i".html{new}
	install -p -m 0644 -- build/"$i".html doc/"$i".html{new}
done
cat package/extra-manpages3 | 
while read i
do
	rm -f -- manual/"$i".3{new}
	install -p -m 0644 -- build/"$i".3 manual/"$i".3{new}
	case "$i" in
	leapsecs)	;;
	*)
		rm -f -- doc/"$i".html{new}
		install -p -m 0644 -- build/"$i".html doc/"$i".html{new}
		;;
	esac
done
cat package/aliases3 | 
while read c a
do
	ln -f -- manual/"$c".3{new} manual/"$a".3{new}
	ln -f -- doc/"$c".html{new} doc/"$a".html{new}
done
cat package/commands8 package/extra-manpages8 | 
while read i
do
	rm -f -- manual/"$i".8{new}
	install -p -m 0644 -- build/"$i".8 manual/"$i".8{new}
	rm -f -- doc/"$i".html{new}
	install -p -m 0644 -- build/"$i".html doc/"$i".html{new}
done
# Headers and libraries
cat package/headers | 
while read i
do
	rm -f -- header/"$i".h{new}
	install -p -m 0644 -- build/"$i".h header/"$i".h{new}
done
cat package/libraries | 
while read i
do
	rm -f -- library/"$i".h{new}
	install -p -m 0644 -- build/"$i".a library/"$i".a{new}
done
# Other guide pages
for i in COPYING
do
	rm -f -- doc/"$i"{new}
	install -p -m 0644 -- build/"$i" doc/"$i"{new}
done
for i in dnsroots.global leapsecs.dat
do
	install -p -m 0644 -- build/"$i" config/"$i"{new}
done

# ##############################################################################
# Rename the ...{new} files in ./command, ./config, and ./manual.
cat package/commands1 package/commands8 | while read i
do
	mv -f -- command/"$i"{new} command/"$i"
done
# All of the commands that have their own manual pages
cat package/commands1 package/extra-manpages1 | 
while read i
do
	mv -f -- manual/"$i".1{new} manual/"$i".1
	mv -f -- doc/"$i".html{new} doc/"$i".html
done
cat package/extra-manpages3 | 
while read i
do
	mv -f -- manual/"$i".3{new} manual/"$i".3
	case "$i" in
	leapsecs)	;;
	*)		mv -f -- doc/"$i".html{new} doc/"$i".html ;;
	esac
done
cat package/commands8 package/extra-manpages8 | 
while read i
do
	mv -f -- manual/"$i".8{new} manual/"$i".8
	mv -f -- doc/"$i".html{new} doc/"$i".html
done
cat package/aliases3 | 
while read c a
do
	mv -f -- manual/"$a".3{new} manual/"$a".3
	mv -f -- doc/"$a".html{new} doc/"$a".html
done
# Headers and libraries
cat package/headers | 
while read i
do
	mv -f -- header/"$i".h{new} header/"$i".h
done
cat package/libraries | 
while read i
do
	mv -f -- library/"$i".a{new} library/"$i".a
done
# Other doco
for i in COPYING
do
	mv -f -- doc/"$i"{new} doc/"$i"
done
for i in dnsroots.global leapsecs.dat
do
	mv -f -- config/"$i"{new} config/"$i"
done
